import type { WebsiteTemplate } from './types'

/** Badminton Club — Minimal Single Column, Inter, tournament focus */
export const badmintonTemplate: WebsiteTemplate = {
  id: 'badminton',
  slug: 'badminton',
  name: 'Badminton Club',
  nameSv: 'Badmintonklubb',
  description: 'Clean, minimal design with tournament and ranking emphasis. Maximum whitespace.',
  sport: 'badminton',
  pattern: 'Minimal Single Column',
  style: 'Minimal & Clean',
  fonts: {
    heading: '"Inter", sans-serif',
    body: '"Inter", sans-serif',
    googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap',
  },
  light: {
    primary: '#171717',
    onPrimary: '#FFFFFF',
    secondary: '#404040',
    accent: '#A16207',
    background: '#FFFFFF',
    foreground: '#171717',
    muted: '#F5F5F5',
    mutedForeground: '#737373',
    border: '#E5E5E5',
    card: '#FAFAFA',
    cardForeground: '#171717',
    heroOverlay: 'linear-gradient(to bottom, transparent 0%, rgba(255,255,255,0.85) 100%)',
    navbar: 'rgba(255,255,255,0.96)',
    destructive: '#DC2626',
  },
  dark: {
    primary: '#FAFAFA',
    onPrimary: '#171717',
    secondary: '#A3A3A3',
    accent: '#D4AF37',
    background: '#0A0A0A',
    foreground: '#FAFAFA',
    muted: '#171717',
    mutedForeground: '#A3A3A3',
    border: '#262626',
    card: '#171717',
    cardForeground: '#FAFAFA',
    heroOverlay: 'linear-gradient(to bottom, transparent 0%, rgba(10,10,10,0.9) 100%)',
    navbar: 'rgba(10,10,10,0.96)',
    destructive: '#EF4444',
  },
  heroVariant: 'minimal',
  sectionStyles: { fixtures: 'compact', players: 'grid', leagueTable: 'minimal' },
  spacing: { section: '5.5rem', container: '64rem', radius: '0.375rem' },
}
