import type { WebsiteTemplate } from './types'

/** Cricket Club — Event/Conference pattern, scorecard-focused fixtures */
export const cricketTemplate: WebsiteTemplate = {
  id: 'cricket',
  slug: 'cricket',
  name: 'Cricket Club',
  nameSv: 'Cricketklubb',
  description: 'Traditional cricket aesthetic with match schedules, scorecards, and player profiles.',
  sport: 'cricket',
  pattern: 'Event/Conference Landing',
  style: 'Vibrant & Block-based',
  fonts: {
    heading: '"Inter", sans-serif',
    body: '"Inter", sans-serif',
    googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap',
  },
  light: {
    primary: '#166534',
    onPrimary: '#FFFFFF',
    secondary: '#15803D',
    accent: '#CA8A04',
    background: '#F0FDF4',
    foreground: '#14532D',
    muted: '#DCFCE7',
    mutedForeground: '#166534',
    border: '#BBF7D0',
    card: '#FFFFFF',
    cardForeground: '#14532D',
    heroOverlay: 'linear-gradient(to top, rgba(20,83,45,0.95) 0%, rgba(20,83,45,0.45) 55%, transparent 100%)',
    navbar: 'rgba(240,253,244,0.94)',
    destructive: '#DC2626',
  },
  dark: {
    primary: '#22C55E',
    onPrimary: '#052E16',
    secondary: '#4ADE80',
    accent: '#FBBF24',
    background: '#052E16',
    foreground: '#DCFCE7',
    muted: '#0A3D1F',
    mutedForeground: '#86EFAC',
    border: '#14532D',
    card: '#0A3D1F',
    cardForeground: '#DCFCE7',
    heroOverlay: 'linear-gradient(to top, rgba(5,46,22,0.98) 0%, rgba(5,46,22,0.55) 55%, transparent 100%)',
    navbar: 'rgba(5,46,22,0.94)',
    destructive: '#EF4444',
  },
  heroVariant: 'split',
  sectionStyles: { fixtures: 'scorecard', players: 'roster', leagueTable: 'striped' },
  spacing: { section: '4.5rem', container: '76rem', radius: '0.75rem' },
}
