import type { WebsiteTemplate } from './types'

/** Football Club — Action-oriented, Russo One + Chakra Petch */
export const footballTemplate: WebsiteTemplate = {
  id: 'football',
  slug: 'football',
  name: 'Football Club',
  nameSv: 'Fotbollsklubb',
  description: 'Bold, action-oriented design with fixture emphasis and league table prominence.',
  sport: 'football',
  pattern: 'Comparison Table + CTA',
  style: 'Vibrant & Block-based',
  fonts: {
    heading: '"Russo One", sans-serif',
    body: '"Chakra Petch", sans-serif',
    googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@300;400;500;600;700&family=Russo+One&display=swap',
  },
  light: {
    primary: '#15803D',
    onPrimary: '#FFFFFF',
    secondary: '#16A34A',
    accent: '#DC2626',
    background: '#F0FDF4',
    foreground: '#14532D',
    muted: '#DCFCE7',
    mutedForeground: '#166534',
    border: '#86EFAC',
    card: '#FFFFFF',
    cardForeground: '#14532D',
    heroOverlay: 'linear-gradient(135deg, rgba(20,83,45,0.92) 0%, rgba(20,83,45,0.35) 100%)',
    navbar: 'rgba(240,253,244,0.95)',
    destructive: '#DC2626',
  },
  dark: {
    primary: '#22C55E',
    onPrimary: '#052E16',
    secondary: '#4ADE80',
    accent: '#EF4444',
    background: '#0A1F0F',
    foreground: '#DCFCE7',
    muted: '#0F2D18',
    mutedForeground: '#86EFAC',
    border: '#14532D',
    card: '#0F2D18',
    cardForeground: '#DCFCE7',
    heroOverlay: 'linear-gradient(135deg, rgba(10,31,15,0.97) 0%, rgba(10,31,15,0.4) 100%)',
    navbar: 'rgba(10,31,15,0.95)',
    destructive: '#EF4444',
  },
  heroVariant: 'diagonal',
  sectionStyles: { fixtures: 'timeline', players: 'cards', leagueTable: 'striped' },
  spacing: { section: '5rem', container: '80rem', radius: '0.5rem' },
}
