import type { WebsiteTemplate } from './types'

/** Hockey Club — Fast-paced, ice blue + navy, Righteous + Poppins */
export const hockeyTemplate: WebsiteTemplate = {
  id: 'hockey',
  slug: 'hockey',
  name: 'Hockey Club',
  nameSv: 'Hockeyklubb',
  description: 'Energetic design with squad roster focus and dynamic visual rhythm.',
  sport: 'hockey',
  pattern: 'Portfolio Grid',
  style: 'Vibrant & Block-based',
  fonts: {
    heading: '"Righteous", sans-serif',
    body: '"Poppins", sans-serif',
    googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&family=Righteous&display=swap',
  },
  light: {
    primary: '#0EA5E9',
    onPrimary: '#FFFFFF',
    secondary: '#0284C7',
    accent: '#F59E0B',
    background: '#F0F9FF',
    foreground: '#0C4A6E',
    muted: '#E0F2FE',
    mutedForeground: '#0369A1',
    border: '#BAE6FD',
    card: '#FFFFFF',
    cardForeground: '#0C4A6E',
    heroOverlay: 'linear-gradient(to right, rgba(12,74,110,0.95) 0%, rgba(12,74,110,0.3) 70%, transparent 100%)',
    navbar: 'rgba(240,249,255,0.94)',
    destructive: '#DC2626',
  },
  dark: {
    primary: '#38BDF8',
    onPrimary: '#082F49',
    secondary: '#7DD3FC',
    accent: '#FBBF24',
    background: '#0C1929',
    foreground: '#E0F2FE',
    muted: '#0F2744',
    mutedForeground: '#7DD3FC',
    border: '#164E63',
    card: '#0F2744',
    cardForeground: '#E0F2FE',
    heroOverlay: 'linear-gradient(to right, rgba(12,25,41,0.98) 0%, rgba(12,25,41,0.45) 70%, transparent 100%)',
    navbar: 'rgba(12,25,41,0.94)',
    destructive: '#EF4444',
  },
  heroVariant: 'fullscreen',
  sectionStyles: { fixtures: 'compact', players: 'roster', leagueTable: 'classic' },
  spacing: { section: '4rem', container: '76rem', radius: '0.25rem' },
}
