import type { WebsiteTemplate } from './types'

/** Generic Multi-Sport — Vibrant & Block-based, Barlow Condensed */
export const multiSportTemplate: WebsiteTemplate = {
  id: 'multi-sport',
  slug: 'multi-sport',
  name: 'Generic Multi-Sport Club',
  nameSv: 'Allround idrottsklubb',
  description: 'Versatile block layout for clubs with multiple sports. Warm, welcoming community feel.',
  sport: 'multi_sport',
  pattern: 'Community/Forum Landing',
  style: 'Vibrant & Block-based',
  fonts: {
    heading: '"Barlow Condensed", sans-serif',
    body: '"Barlow", sans-serif',
    googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;500;600;700&family=Barlow:wght@300;400;500;600;700&display=swap',
  },
  light: {
    primary: '#DC2626',
    onPrimary: '#FFFFFF',
    secondary: '#EF4444',
    accent: '#CA8A04',
    background: '#FEF2F2',
    foreground: '#7F1D1D',
    muted: '#FEE2E2',
    mutedForeground: '#991B1B',
    border: '#FECACA',
    card: '#FFFFFF',
    cardForeground: '#7F1D1D',
    heroOverlay: 'linear-gradient(to top, rgba(127,29,29,0.95) 0%, rgba(127,29,29,0.4) 60%, transparent 100%)',
    navbar: 'rgba(254,242,242,0.92)',
    destructive: '#DC2626',
  },
  dark: {
    primary: '#EF4444',
    onPrimary: '#FFFFFF',
    secondary: '#F87171',
    accent: '#FBBF24',
    background: '#1C0A0A',
    foreground: '#FEE2E2',
    muted: '#2D1515',
    mutedForeground: '#FCA5A5',
    border: '#450A0A',
    card: '#2D1515',
    cardForeground: '#FEE2E2',
    heroOverlay: 'linear-gradient(to top, rgba(28,10,10,0.98) 0%, rgba(28,10,10,0.5) 60%, transparent 100%)',
    navbar: 'rgba(28,10,10,0.92)',
    destructive: '#EF4444',
  },
  heroVariant: 'classic',
  sectionStyles: { fixtures: 'cards', players: 'grid', leagueTable: 'classic' },
  spacing: { section: '4rem', container: '72rem', radius: '1rem' },
}
